#!/bin/bash

# Get the network interface and state
INTERFACE="$1"
STATE="$2"

# Check if the interface is in the 'up' state
if [[ "$STATE" == "up" ]]; then
    # Get the connected SSID
    SSID=$(iwgetid -r)
    CON_STATUS=$(nc -zw1 google.com 443 >/dev/null 2>&1; echo $?)
    
    # Check if the connected SSID is 'ibbWiFi'
    if [[ "$SSID" == "ibbWiFi" ]]; then
	    if [ "$CON_STATUS" -eq 0 ]; then
		    echo "$(date): Connected to ibbWifi and Online" >> /var/log/ibbwifi-autologin.log
	    else
		    echo "$(date): Connected to ibbWiFi on $INTERFACE. Running script..." >> /var/log/ibbwifi-autologin.log
		    python3 /home/typefe/Desktop/w/PROGRAMMING/PYTHON/Exercise/captive_auto_login/script.py
	    fi
    else
        echo "$(date): Connected to $SSID on $INTERFACE. No action required." >> /var/log/ibbwifi-autologin.log
    fi
fi

